[package]
name = "yatp"
version = "0.0.1"
authors = ["The TiKV Authors"]
edition = "2018"
description = ""
readme = "README.md"
license = "Apache-2.0"
repository = "https://github.com/tikv/yatp/"

[dependencies]
num_cpus = "1.0"
parking_lot_core = "0.7"
crossbeam-deque = "0.7"
rand = { version = "0.7", features = ["small_rng"] }
init_with = "1.1.0"
dashmap = "1.2.0"
uuid = { version = "0.8", features = ["v4"] }